### ISSUE TITLE
data did not match any variant of untagged enum PyDecoderWrapper

### ISSUE THREAD

**Issue by copperdong** [xverse-ai/XVERSE-7B#1]
加载时出现了错误，麻烦看看怎么解决，谢谢
```
Traceback (most recent call last):
  File "chat_demo.py", line 67, in <module>
    init_model(args)
  File "chat_demo.py", line 22, in init_model
    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer_path, truncation_side="left", padding_side="left")
  File "/home/yons/anaconda3/envs/opennmtpy/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 727, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/yons/anaconda3/envs/opennmtpy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/home/yons/anaconda3/envs/opennmtpy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/yons/anaconda3/envs/opennmtpy/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum PyDecoderWrapper at line 92 column 3
```

**Comment by underspirit** [comment]
使用的transformers和tokenizers包是什么版本, 可以尝试升级

**Comment by littlerookie** [comment]
使用最新版本的Transformers==4.43.3，tokenizers==0.19.1, vllm==0.5.3.post1，报相同的错

**Comment by underspirit** [comment]
你好, 这个是tokenizer的兼容性问题
可以使用 https://huggingface.co/xverse/XVERSE-13B-256K 中的tokenizer文件, 这份已经经过处理

**Comment by kkk112** [comment]
相隔半年時間，部分測試代碼需要更新，以下是目前我在WIndows10 22H2，在VS Code運行的新版簡單代碼示例，實測在8bit量化下生成總花費時間約16秒。感謝樓上的指導，我想分享詳細複述給新手小白們知道步驟，需到XVERSE-13B的github下載**tokennizer.json.update**和**tokenizer_config.json.update**來替換原本的json文件，經測試13B的文件在7B同樣適用。謝謝大神提供模型讓我這個新手也能學習使用

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from transformers.generation.utils import GenerationConfig
import sys
sys.stdout.reconfigure(encoding='utf-8')# 8-bit quantization
quantization_config_8bit = BitsAndBytesConfig(
    load_in_8bit=True,
)
model_path = "./XVERSE-7B-Chat"
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    # torch_dtype=torch.bfloat16, # You can remove '#''if you don't need to quantize this model 
    trust_remote_code=True,
    device_map='auto',
    quantization_config=quantization_config_8bit,)
model.generation_config = GenerationConfig.from_pretrained(model_path)
model = model.eval()
tokenizer = AutoTokenizer.from_pretrained(
    model_path,
    trust_remote_code=True)
history = [{"role": "user", "content": "接下來我向你提問後請你將回答的簡體字翻譯成繁體中文告訴我。1955年的美國總統是誰？他隸屬於哪個黨派？"}]
response = model.chat(tokenizer, history)
print(response)


設備配置：
R9 3900 @4.15G
RTX 2080Ti 11G
