### ISSUE TITLE
我想对该模型进行微调，不知官方有没有测试

### ISSUE THREAD

**Issue by ChuXNobody** [xverse-ai/XVERSE-7B#2]
在文档中，官方给出的所使用设备与13b同出一致，nvidia*8 80GB 的卡进行全量微调，这不亚于是在训练模型  8 * Nvidia A800 80 GB + DeepSpeed  我想问是否能用 nvidia 4090 24GB RAM 进行lora权重微调，fp16微调训练

**Comment by underspirit** [comment]
可以参考README的模型微调部分的说明
